name: diff-files

on:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  change-detection:
    name: Detect any changed files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: json
          filters: |
            fc:
              - test_diff/**
      - name: Print the changes
        run: |
          echo '${{ steps.filter.outputs.fc_files }}' | jq
        id: jq
